enable more tests

diff --git a/.github/workflows/_test_nightly_python_source.yml b/.github/workflows/_test_nightly_python_source.yml
--- a/.github/workflows/_test_nightly_python_source.yml
+++ b/.github/workflows/_test_nightly_python_source.yml
@@ -17,6 +17,8 @@ on:
         type: string
         # options:
         #   - ubuntu-latest
+        #   - windows-latest
+        #   - ubuntu-24.04-arm
         description: The kind of runner to use
         required: true
       num-workers:
@@ -70,6 +72,7 @@ jobs:
         uses: ./.github/actions/build-source
         with:
           build-iceberg: true
+          build-bodosql: ${{ startsWith(inputs.test-type, 'sql') }}
           environment: "default"
       - name: Clean Maven and Spark Ivy Cache
         run: |
@@ -87,9 +90,54 @@ jobs:
             pip install --no-deps 'git+https://github.com/apache/polaris.git@release/1.0.x#subdirectory=client/python'
       - name: Run Tests
         run: |
-          python -m bodo.runtests "${{ runner.os }}" "${{ inputs.num-workers }}" --pyargs bodo -s -v -m "$PYTEST_MARKER"
+          # For caching tests we need to update the location of the decryption file.
+          # We set the absolute path as an environment variable.
+          export BODO_TRACING_DECRYPTION_FILE_PATH="$WORKING_DIR/buildscripts/decompress_traces.py"
+
+          # Ignore streaming/caching/metadata tests in Dataframes/Spawn mode to avoid importing JIT during test collection.
+          PYTEST_IGNORE="--ignore bodo/tests/test_streaming --ignore bodo/tests/caching_tests"
+
+          if [[ "$TEST_TYPE" == "sql*" ]]; then
+              cd $WORKING_DIR/BodoSQL
+          fi
+
+          if [[ "$TEST_TYPE" == "cache" ]]; then    
+              python -m bodo.runtests_caching "$TEST_NAME" "$NP" bodo/tests/caching_tests
+          elif [[ "$TEST_TYPE" == "spawn" ]]; then
+              # Disabling the DataFrame library for spawn tests since some of the tests
+              # create Pandas manager states for testing that are not fully functional.
+              export BODO_ENABLE_DATAFRAME_LIBRARY=0
+              export BODO_TEST_SPAWN_MODE=1
+              pytest -s -v -Wignore -m "$PYTEST_MARKER" $PYTEST_IGNORE \
+                  bodo/tests --junitxml=pytest-report-spawn-mode.xml --test-run-title="$TEST_NAME"
+          elif [[ "$TEST_TYPE" == "df_lib" ]]; then
+              export BODO_ENABLE_TEST_DATAFRAME_LIBRARY=1
+              pytest -s -v -Wignore -m "$PYTEST_MARKER and not jit_dependency" $PYTEST_IGNORE \
+                  bodo/tests --junitxml=pytest-report-df-library.xml --test-run-title="$TEST_NAME"
+              # Run tests with JIT dependency separately to avoid JIT imports impacting other tests.
+              pytest -s -v -Wignore -m "$PYTEST_MARKER and jit_dependency" $PYTEST_IGNORE \
+                  bodo/tests --junitxml=pytest-report-df-library-jit-dependency.xml --test-run-title="$TEST_NAME - JIT"
+          elif [[ "$TEST_TYPE" == "compiler" ]]; then
+              # Some tests assume a batch size of 4096 for testing specific behavior.
+              export BODO_STREAMING_BATCH_SIZE=4096
+              python -m bodo.runtests "$TEST_NAME" "$NP" --pyargs bodo -s -v -m "$PYTEST_MARKER"
+          elif [[ "$TEST_TYPE" == "sql_cache" ]]; then
+              python -u -m bodosql.runtests_caching "$TEST_NAME" "$NP" bodosql/tests/caching_tests/
+          elif [[ "$TEST_TYPE" == "sql_spawn" ]]; then
+              export BODO_TEST_SPAWN_MODE=1
+              pytest -s -v -p no:faulthandler -Wignore -m "$PYTEST_MARKER" bodosql/tests --junitxml=pytest-report-sql-spawn-mode.xml --test-run-title="$TEST_NAME"
+          elif [[ "$TEST_TYPE" == "sql" ]]; then
+              python -u -m bodosql.runtests "$TEST_NAME" "$NP" -s -v -p no:faulthandler -m "$PYTEST_MARKER" bodosql/tests/
+          else
+              echo "Invalid TEST_TYPE: $TEST_TYPE"
+              exit 1
+          fi
         env:
-          BODO_STREAMING_BATCH_SIZE: 4096 
+          WORKING_DIR: ${{ github.workspace }}
+          TEST_NAME: "${{ github.run_id }}-${{ inputs.test-type }}"
+          TEST_TYPE: ${{ inputs.test-type }}
+          NP: ${{ inputs.num-workers }}
+          BODO_NUM_WORKERS: ${{ inputs.num-workers }}
           BODO_SPAWN_MODE: "0"
           BODO_BUFFER_POOL_REMOTE_MODE: "1"
           BODO_BUFFER_POOL_DEBUG_MODE: "1"
