Fix hosts

diff --git a/.github/workflows/_test_python_source.yml b/.github/workflows/_test_python_source.yml
--- a/.github/workflows/_test_python_source.yml
+++ b/.github/workflows/_test_python_source.yml
@@ -65,6 +65,19 @@ jobs:
         - name: Install Extra Test dependencies
           # This isn't published on pypi so no good way to list it as a dependency
           run: pip install 'git+https://github.com/apache/polaris.git#subdirectory=client/python'
+        - name: fix /etc/hosts
+          # On multiple occasions GitHub added things to /etc/hosts that are not
+          # correct syntax for this file causing test failures:
+          #   https://github.com/actions/runner-images/issues/3353
+          #   https://github.com/actions/runner-images/issues/12192
+          # Just clearing those out, if any.
+          run: |
+            set -x
+            cp /etc/hosts ./hosts.bak
+            sed -E -n \
+              '/^[[:space:]]*(#.*|[0-9a-fA-F:.]+([[:space:]]+[a-zA-Z0-9.-]+)+|)$/p' \
+              ./hosts.bak | sudo tee /etc/hosts
+            diff -u ./hosts.bak /etc/hosts || true
 
         # Run Tests
         - name: Run Tests
@@ -127,12 +140,6 @@ jobs:
             BODO_SPAWN_MODE: "0"
             BODO_BUFFER_POOL_REMOTE_MODE: "1"
             BODO_BUFFER_POOL_DEBUG_MODE: "1"
-            # Pyspark Config
-            SPARK_LOCAL_IP: 127.0.0.1
-            PYSPARK_SUBMIT_ARGS: >
-              --conf spark.driver.bindAddress=127.0.0.1 
-              --conf spark.driver.host=127.0.0.1 
-              pyspark-shell
             # Testing Credentials
             SF_USERNAME: ${{ secrets.SF_USERNAME }}
             SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
